library(tidyverse)

charlson_score <- cbind("Comorbidity" = c("Prior myocardial infarction",
                                          "Congestive heart failure",
                                          "Peripheral vascular disease",
                                          "Cerebrovascular disease",
                                          "Dementia",
                                          "Chronic pulmonary disease",
                                          "Rheumatologic disease",
                                          "Peptic ulcer disease",
                                          "Mild liver disease",
                                          "Diabetes",
                                          "Cerebrovascular (hemiplegia) event",
                                          "Moderate-to-severe renal disease",
                                          "Diabetes with chronic complications",
                                          "Cancer without metastases",
                                          "Leukaemia",
                                          "Lymphoma",
                                          "Moderate to severe liver disease",
                                          "Metastatic solid tumour",
                                          "Acquired immuno-deficiency syndrome (AIDS)"),
                        "Score" = c(1,
                                    1,
                                    1,
                                    1,
                                    1,
                                    1,
                                    1,
                                    1,
                                    1,
                                    1,
                                    2,
                                    2,
                                    2,
                                    2,
                                    2,
                                    2,
                                    3,
                                    6,
                                    6)) %>% as_tibble()

charlson_score_table <- charlson_score %>% gt() %>% gt_theme_espn()